name: Close Stale Issues

on:
  workflow_dispatch:  # ← Allows you to run it manually


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale. Please update or it will be closed.'
          close-issue-message: 'Closing stale issue.'
          days-before-stale: 0
          days-before-close: 0
