name: pass file to other stage

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "version=1.0.3" > version.txt
      - uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: version.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: version-file
      - run: |
          echo "Deploying version:"
          cat version.txt
