name: Terraform, Docker and Ansible

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  # ==========================================================
  # JOB 1 - Terraform
  # ==========================================================
  terraform:
    name: Terraform Azure VM
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

    
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Terraform/AzureVm
        run: terraform init

      # - name: Terraform Format
      #   working-directory: Terraform/AzureVm
      #   run: terraform fmt -check

      - name: Terraform Validate
        working-directory: Terraform/AzureVm
        run: terraform validate

      - name: Terraform Plan
        working-directory: Terraform/AzureVm
        run: |
          terraform plan \
            -var="ssh_public_key_path=${{ github.workspace }}/keys/id_rsa.pub" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: Terraform/AzureVm
        run: terraform apply -auto-approve tfplan


  # ==========================================================
  # JOB 2 - Docker Build and Push
  # ==========================================================
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    needs: terraform

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image 
        run: |
          pwd
          ls
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest ./Dockerfile
            

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest


  # ==========================================================
  # JOB 3 - Ansible
  # ==========================================================
  ansible:
    name: Ansible Configure Azure VM
    runs-on: ubuntu-latest

    needs:
      - terraform
      - docker

    steps:

      # ------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # Install Ansible
      # ------------------------------------------------------
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # ------------------------------------------------------
      # Create SSH Private Key
      # ------------------------------------------------------
      - name: Create SSH Private Key
        run: |
          echo '${{ secrets.SSH_KEY }}' > private_key
          chmod 600 private_key

      # ------------------------------------------------------
      # Get Azure VM Public IP
      # ------------------------------------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Get VM Public IP
        id: vm_ip
        run: |
          VM_IP=$(az vm list-ip-addresses \
            --resource-group kml_rg_main-82b78f8686044449 \
            --name KIRAN \
            --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress" \
            --output tsv)

          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

          echo "Azure VM IP: $VM_IP"

      # ------------------------------------------------------
      # Test SSH Connection
      # ------------------------------------------------------
      - name: Test SSH Connection
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -i private_key \
            azureuser@$VM_IP \
            "hostname && whoami"

      # ------------------------------------------------------
      # Run Ansible
      # ------------------------------------------------------
      - name: Run Ansible
        run: |
          ansible-playbook \
            -i "${VM_IP}," \
            -u azureuser \
            --private-key private_key \
            -e "docker_image=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest" \
            Ansible/playbook.yml

